name: Build and Test BP Calculator

on:
  push:
    branches:
      - master

jobs:
  build_and_unit_test:
    name: build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
      - name: Build, Run Unit tests, Generate code coverage
        run: | 
          dotnet build -c Release
          dotnet test bpUnitTestProject/bpUnitTestProject.csproj --collect "XPlat Code coverage"
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"./bpUnitTestProject/TestResults/*/coverage.cobertura.xml" -targetdir:"./bpUnitTestProject/coverage-report" -reporttypes:Html

      - name: Publish test results and code coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: ./bpUnitTestProject/TestResults/

      - name: Upload code coverage HTML report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html-report
          path: ./bpUnitTestProject/coverage-report/
  
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build_and_unit_test  # Ensures deployment runs only if build and tests pass
    environment:
      name: Test
      url: test-bpcalculator.azurewebsites.net
    env: 
      AZURE_WEBAPP_NAME: test-bpcalculator
      AZURE_WEBAPP_PACKAGE_PATH: 'publish'
    steps:
      - uses: actions/checkout@v4
      
      # publish web app 
      - name: Publish web app
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
      
        # Deploy to Azure app service
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}                            
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # slot-name: staging TODO-Remove: Not available on free accounts
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
