name: Build and Test BP Calculator

on:
  push:
    branches:
      - master

jobs:
  build_and_unit_test:
    name: build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
      - name: Build release
        run: dotnet build -c Release
      - name: Run unit tests
        run: dotnet test bpUnitTestProject/bpUnitTestProject.csproj --collect "Code coverage"